//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ЗаёЗ.rc
//
#define IDR_MENU1                       101
#define IDB_BACKGROUND1                 102
#define IDB_BFACE                       103
#define IDB_SADFACE                     104
#define IDB_SMILEFACE                   105
#define IDB_BODY                        106
#define IDB_LEFTARM                     107
#define IDB_RIGHTARM                    108
#define IDB_LEGS                        109
#define IDB_DHEAD                       110
#define IDB_BLOODBODY                   111
#define IDB_BLOODBODY2                  111
#define IDB_TREE                        112
#define IDB_UNDERSCORE                  113
#define IDB_INFO                        114
#define IDB_A0_1                        132
#define IDB_A0_2                        133
#define IDB_A0_3                        134
#define IDB_A0_4                        135
#define IDB_A0_5                        136
#define IDB_A0_6                        137
#define IDB_A1_1                        138
#define IDB_A1_2                        139
#define IDB_A1_3                        140
#define IDB_A1_4                        141
#define IDB_A1_5                        142
#define IDB_A1_6                        143
#define IDB_A2_1                        144
#define IDB_A2_2                        145
#define IDB_A2_3                        146
#define IDB_A2_4                        147
#define IDB_A2_5                        148
#define IDB_A2_6                        149
#define IDB_B                           150
#define IDB_C                           151
#define IDB_D0                          152
#define IDB_D1                          153
#define IDB_E0_1                        154
#define IDB_E0_2                        155
#define IDB_E0_3                        156
#define IDB_E0_4                        157
#define IDB_E0_5                        158
#define IDB_E0_6                        159
#define IDB_E1_1                        160
#define IDB_E1_2                        161
#define IDB_E1_3                        162
#define IDB_E1_4                        163
#define IDB_E1_5                        164
#define IDB_E1_6                        165
#define IDB_F                           166
#define IDB_G                           167
#define IDB_H                           168
#define IDB_I_1                         169
#define IDB_I_2                         170
#define IDB_I_3                         171
#define IDB_I_4                         172
#define IDB_I_5                         173
#define IDB_I_6                         174
#define IDB_J                           175
#define IDB_K                           176
#define IDB_L                           177
#define IDB_M                           178
#define IDB_N                           179
#define IDB_O0_1                        180
#define IDB_O0_2                        181
#define IDB_O0_3                        182
#define IDB_O0_4                        183
#define IDB_O0_5                        184
#define IDB_O0_6                        185
#define IDB_O1_1                        186
#define IDB_O1_2                        187
#define IDB_O1_3                        188
#define IDB_O1_4                        189
#define IDB_O1_5                        190
#define IDB_O1_6                        191
#define IDB_O2_1                        192
#define IDB_O2_2                        193
#define IDB_O2_3                        194
#define IDB_O2_4                        195
#define IDB_O2_5                        196
#define IDB_O2_6                        197
#define IDB_P                           198
#define IDB_Q                           199
#define IDB_R                           200
#define IDB_S                           201
#define IDB_T                           202
#define IDB_U0_1                        203
#define IDB_U0_2                        204
#define IDB_U0_3                        205
#define IDB_U0_4                        206
#define IDB_U0_5                        207
#define IDB_U0_6                        208
#define IDB_U1_1                        209
#define IDB_U1_2                        210
#define IDB_U1_3                        211
#define IDB_U1_4                        212
#define IDB_U1_5                        213
#define IDB_U1_6                        214
#define IDB_V                           215
#define IDB_W                           216
#define IDB_X                           217
#define IDB_Y                           218
#define IDB_Z                           219
#define IDB_N0                          220
#define IDB_N1                          221
#define IDB_N2                          222
#define IDB_N3                          223
#define IDB_N4                          224
#define IDB_N5                          225
#define IDB_N6                          226
#define IDB_N7                          227
#define IDB_N8                          228
#define IDB_N9                          229
#define IDI_ICON1                       234
#define ID_HELP_MANUAL                  40003
#define ID_HELP_TIP                     40004
#define ID_FILE_EXIT                    40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
